const ADD_DOGS = "ADD_DOGS";
const ADD_DOG_FAVORITE = "ADD_DOG_FAVORITE";
const DELETE_DOG_FAVORITE = "DELETE_DOG_FAVORITE";

const NAME_STORAGE_FAVORITES = '890as7das87';

export {
    ADD_DOGS,
    ADD_DOG_FAVORITE,
    DELETE_DOG_FAVORITE,
    NAME_STORAGE_FAVORITES
}